{% set name = "spopt" %}
{% set version = "0.5.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47c258dda26c9f51e14edec6d0d73d218c6143a5a6d434a6e1fdca20b9c7cf0a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - geopandas >=0.10.0
    - libpysal
    - networkx
    - numpy >=1.21
    - pandas >=1.0.5
    - pulp
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - spaghetti
    - tqdm >=4.27.0

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pysal.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'spopt: Spatial Optimization'
  description: |
    Spopt is an open-source Python library for solving optimization problems with spatial data. Originating from the `region` module in [PySAL](http://pysal.org) (Python Spatial Analysis Library), it is under active development for the inclusion of newly proposed models and methods for regionalization, facility location, and transportation-oriented solutions.
  doc_url: https://pysal.org/{{ name }}/
  dev_url: http://github.com/pysal/{{ name }}

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - xf37
    - gegen07
