schema_version: 1

context:
  python_min: "3.11"
  name: spopt
  version: "0.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ed599b8c0e219682e48e85852b615dbc6f122ef2907d73c11894ad3ffdb39d47

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=${{ python_min }}
    - geopandas >=0.14.0
    - libpysal >=4.10.0
    - mapclassify >=2.7.0
    - networkx >=3.2
    - numpy >=1.26.0
    - pandas >=2.1.0
    - pointpats >=2.4.0
    - pulp >=2.8
    - scikit-learn >=1.4.0
    - scipy >=1.12.0
    - shapely >=2.1.1
    - spaghetti >=1.7.4
    - tqdm >=4.66.0

tests:
  - python:
      imports:
        - ${{ name }}
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: "spopt: Spatial Optimization"
  description: |
    Spopt is an open-source Python library for solving optimization problems with spatial data. Originating from the `region` module in [PySAL](http://pysal.org) (Python Spatial Analysis Library), it is under active development for the inclusion of newly proposed models and methods for regionalization, facility location, and transportation-oriented solutions.
  homepage: http://pysal.org/
  repository: http://github.com/pysal/${{ name }}
  documentation: https://pysal.org/${{ name }}/

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - xf37
    - gegen07
    - martinfleis
