schema_version: 1

context:
  python_min: "3.12"
  name: spopt
  version: "0.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4c74d8675d0d178cf0ae217315cbfd2c2259808298faea271909f30d154bdc9b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=${{ python_min }}
    - geopandas >=1.1.0
    - libpysal >=4.12.0
    - mapclassify >=2.9.0
    - networkx >=3.4
    - numpy >=2.0.0
    - pandas >=2.3.0
    - pointpats >=2.5.2
    - pulp >=3.2,<4
    - scikit-learn >=1.5.0
    - scipy >=1.14.0
    - shapely >=2.1.1
    - spaghetti >=1.7.4
    - tqdm >=4.67.0

tests:
  - python:
      imports:
        - ${{ name }}
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: "spopt: Spatial Optimization"
  description: |
    Spopt is an open-source Python library for solving optimization problems with spatial data. Originating from the `region` module in [PySAL](http://pysal.org) (Python Spatial Analysis Library), it is under active development for the inclusion of newly proposed models and methods for regionalization, facility location, and transportation-oriented solutions.
  homepage: http://pysal.org/
  repository: http://github.com/pysal/${{ name }}
  documentation: https://pysal.org/${{ name }}/

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - xf37
    - gegen07
    - martinfleis
